### ISSUE TITLE
Publish provider to Terraform Registry

### ISSUE THREAD

**Issue by Djiit** [kaleido-io/terraform-provider-kaleido#13]
Hey team,

It would be awesome to be able to download this provider via the new Terraform Registry.
Publishing is really easy since Terraform 0.13.

Any chance you can publish it here https://registry.terraform.io/publish/provider  ? 

Thanks!

**Comment by peterbroadhurst** [comment]
Hi @Djiit

The provider is now available here: https://registry.terraform.io/providers/kaleido-io/kaleido/latest

Sorry for the delay on this, we wanted to address some important outstanding features in the terraform provider code before publishing. While we've had significant usage of the terraform provider over the past years, it's all been from experienced developers that have been aware of the limitations (and in many cases contributed directly to the code).

The biggest two limitations we've addressed are:
- Special to Kaleido (compared to most Cloud APIs), is the decentralized model multiple parties need to use separate accounts to administer nodes within the same business network. The `shared_deployment` field added to a number of resources addresses that restriction. So now multiple separate terraform templates can contribute nodes to a single environment.
- Update support for fields that a not core to a resource's identity - `name`,`size`,`details`,`kms_id` etc. on nodes for example. Previously updates would actually results in delete + recreate of resources, which was a big point of confusion.

There are still updates to come, particularly around the documentation and samples.

The summary on the updates so far are in PR #19
