### ISSUE TITLE
Implement Exist and Update

### ISSUE THREAD

**Issue by ricardo-larosa** [kaleido-io/terraform-provider-kaleido#2]
This way the state will sync with previously manually created resources. Like for example: AWS resources.

**Comment by ricardo-larosa** [comment]
I would like to take this one.

**Comment by peterbroadhurst** [comment]
@ricardo-larosa - I believe #19 has now addressed this.

**Comment by ricardo-larosa** [comment]
Cool! @peterbroadhurst
