### ISSUE TITLE
[Bug] Creating Environment 

### ISSUE THREAD

**Issue by ernanirst** [kaleido-io/terraform-provider-kaleido#8]
Hello, I believe there is a bug that is preventing the creation of environments on the Kaleido API. I successfully created the Consortium and Membership with the code below (the same of the `simple_env` example), however, the Environment gets stuck on the `Initializing` phase, and eventually terraform times out.

```
provider "kaleido" {
  api = "https://console${var.kaleido_region}.kaleido.io/api/v1"
  api_key = var.kaleido_api_key
}

resource "kaleido_consortium" "mine" {
  name = "My Kaleido Consortium"
  description = "Deployed with Terraform"
  mode = "single-org"
}

resource "kaleido_membership" "kaleido" {
  consortium_id = kaleido_consortium.mine.id
  org_name = "Me"
}

resource "kaleido_environment" "myEnv" {
  consortium_id = kaleido_consortium.mine.id
  name = "My Environment"
  description = "Deployed with Terraform"
  env_type = element(var.env_types, 0)
  consensus_type = element(var.quorum_consensus, 0)
}
```

I also tried to create the environment directly through the API and I got the exact same issue. The most strange thing is that creating the environment through the web interface works fine and it's almost instantaneous. After looking through the requests that the web interface is doing, apparently, it's using a different API...

Hope someone from Kaleido can help with this.

**Comment by peterbroadhurst** [comment]
Hi @ernanirst
The transition out of `Initializing` on the environment does not occur until the first deployment `zone` is created:
https://api.kaleido.io/platform.html#tag/Zones/paths/~1consortia~1{consortia_id}~1environments~1{environment_id}~1zones/post
This happens automatically when you create the first node in a region.
In the UI the default zone is created automatically.
Please do raise a ticket at `support@kaleido.io` to discuss your specific usage of the API so we can assist you directly in more detail.
